defmodule Chatex.Message do
  use Ecto.Schema
  import Ecto.Changeset

  schema "messages" do
    field(:type, :string)
    field(:payload, :map)
    # Strange id generated by the front
    field(:sid, :string)
    belongs_to :conversation, Chatex.Conversation

    timestamps()
  end

  def changeset(struct, params \\ %{}) do
    struct
    |> cast(params, [:type, :payload, :sid, :conversation_id])
  end
end
