defmodule Chatex.Repo.Migrations.AddMessageTable do
  use Ecto.Migration

  def change do
    create table(:messages) do
      add :type, :string
      add :payload, :map
      # Strange id generated by the front
      add :sid, :string
      add :conversation_id, references(:conversations)
      timestamps()
    end

  end
end

